DROP TABLE IF EXISTS Host;
CREATE TABLE Host(
	host_id	INTEGER PRIMARY KEY AUTOINCREMENT,
	hostname	TEXT	NOT NULL	UNIQUE
);

DROP TABLE IF EXISTS Service;
CREATE TABLE Service(
	service_id	INTEGER PRIMARY KEY AUTOINCREMENT,
	name	TEXT NOT NULL,
	port	INTEGER NOT NULL,
	protocol	TEXT	NOT NULL,
	UNIQUE(name, port, protocol)
);

DROP TABLE IF EXISTS Host_Service;
CREATE TABLE Host_Service(
		host_service_id INTEGER PRIMARY KEY AUTOINCREMENT,
		host_id	INTEGER NOT NULL,
		service_id INTEGER NOT NULL,
		FOREIGN KEY(host_id)	REFERENCES	Host(host_id) ON DELETE CASCADE,
		FOREIGN	KEY(service_id)	REFERENCES	Service(service_id) ON DELETE CASCADE
);
